AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for Expense Splitter Application with CloudFront-only API access'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  JWTSecret:
    Type: String
    NoEcho: true
    Description: JWT Secret for authentication
    MinLength: 32

  CloudFrontDistributionId:
    Type: String
    Description: CloudFront Distribution ID that should have access to API Gateway
    Default: ""

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ExpenseSplitter-Users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ExpenseSplitter

  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ExpenseSplitter-Groups-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ExpenseSplitter

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ExpenseSplitter-Expenses-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: group
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GroupIndex
          KeySchema:
            - AttributeName: group
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ExpenseSplitter

  SettlementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ExpenseSplitter-Settlements-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: group
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GroupIndex
          KeySchema:
            - AttributeName: group
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ExpenseSplitter

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ExpenseSplitter-Lambda-Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt GroupsTable.Arn
                  - !GetAtt ExpensesTable.Arn
                  - !GetAtt SettlementsTable.Arn
                  - !Sub '${UsersTable.Arn}/index/*'
                  - !Sub '${ExpensesTable.Arn}/index/*'
                  - !Sub '${SettlementsTable.Arn}/index/*'
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '*'

  # Lambda Function
  ExpenseSplitterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'expense-splitter-${Environment}'
      Runtime: nodejs18.x
      Handler: lambda.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be updated during deployment' })
            };
          };
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          JWT_SECRET: !Ref JWTSecret
          USERS_TABLE_NAME: !Ref UsersTable
          GROUPS_TABLE_NAME: !Ref GroupsTable
          EXPENSES_TABLE_NAME: !Ref ExpensesTable
          SETTLEMENTS_TABLE_NAME: !Ref SettlementsTable
      Timeout: 30
      MemorySize: 512
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ExpenseSplitter

  # API Gateway with Resource Policy
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'expense-splitter-api-${Environment}'
      Description: API for Expense Splitter Application (CloudFront access only)
      EndpointConfiguration:
        Types:
          - REGIONAL
      Policy: !If
        - HasCloudFrontDistribution
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
              Condition:
                StringEquals:
                  'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}'
            - Effect: Deny
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
              Condition:
                StringNotEquals:
                  'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}'
        - !Ref 'AWS::NoValue'

  # API Gateway Lambda Permission
  ApiGatewayLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ExpenseSplitterFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*'

  # API Gateway Proxy Resource
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method
  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExpenseSplitterFunction.Arn}/invocations'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ProxyMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

Conditions:
  HasCloudFrontDistribution: !Not [!Equals [!Ref CloudFrontDistributionId, ""]]

Outputs:
  ApiUrl:
    Description: API Gateway URL (restricted to CloudFront access only)
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  UsersTableName:
    Description: Users DynamoDB Table Name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'

  GroupsTableName:
    Description: Groups DynamoDB Table Name
    Value: !Ref GroupsTable
    Export:
      Name: !Sub '${AWS::StackName}-GroupsTable'

  ExpensesTableName:
    Description: Expenses DynamoDB Table Name
    Value: !Ref ExpensesTable
    Export:
      Name: !Sub '${AWS::StackName}-ExpensesTable'

  SettlementsTableName:
    Description: Settlements DynamoDB Table Name
    Value: !Ref SettlementsTable
    Export:
      Name: !Sub '${AWS::StackName}-SettlementsTable'

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref ExpenseSplitterFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunction'

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref ApiGateway
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'
